### ISSUE TITLE
Trouble setting up: "AttributeError: 'NoneType' object has no attribute 'list_templates'"

### ISSUE THREAD

**Issue by meric** [syrusakbary/jsjinja#2]
I'm trying to get this running on a django 1.5 site using python 2.7.3.

I entered the shell and tried the following:

```
>>> import jinja2
>>> env = jinja2.Environment(extensions=['jsjinja.ext.JsJinjaExtension',])
>>> env.jsjinja.generate_all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/Eric/Projects/sagesse-env/lib/python2.7/site-packages/jsjinja/__init__.py", line 34, in generate_all
    templates = self.environment.list_templates()
  File "/Users/Eric/Projects/sagesse-env/lib/python2.7/site-packages/jinja2/environment.py", line 639, in list_templates
    x = self.loader.list_templates()
AttributeError: 'NoneType' object has no attribute 'list_templates'
```

What steps am I missing?

On another note, it seems simplejson is a dependency as well, I had to `pip install simplejson` to get it to run.

**Comment by syrusakbary** [comment]
You dont have any template loader associated to the jinja2 environment, so `jsjinja` cannot load the temlates.

**Comment by meric** [comment]
Thanks!
